INSERT INTO public.currencies (id, code, full_name, sign) VALUES (1, 'AUD', 'Australian dollar', 'A$');
INSERT INTO public.currencies (id, code, full_name, sign) VALUES (2, 'USD', 'United States dollar', '$');
INSERT INTO public.currencies (id, code, full_name, sign) VALUES (3, 'EUR', 'Euro', '€');
INSERT INTO public.currencies (id, code, full_name, sign) VALUES (4, 'RUB', 'Russian ruble', '₽');
INSERT INTO public.currencies (id, code, full_name, sign) VALUES (5, 'GBP', 'Pound sterling', '£');
INSERT INTO public.currencies (id, code, full_name, sign) VALUES (6, 'JPY', 'Japanese yen', '¥');
INSERT INTO public.currencies (id, code, full_name, sign) VALUES (7, 'CNY', 'Chinese yuan', '¥');
INSERT INTO public.currencies (id, code, full_name, sign) VALUES (8, 'CHF', 'Swiss franc', 'CHF');
INSERT INTO public.currencies (id, code, full_name, sign) VALUES (9, 'CAD', 'Canadian dollar', 'C$');
INSERT INTO public.currencies (id, code, full_name, sign) VALUES (10, 'NZD', 'New Zealand dollar', 'NZ$');
INSERT INTO public.currencies (id, code, full_name, sign) VALUES (11, 'TRY', 'Turkish lira', '₺');
INSERT INTO public.currencies (id, code, full_name, sign) VALUES (12, 'THB', 'Thai baht', '฿');
INSERT INTO public.currencies (id, code, full_name, sign) VALUES (13, 'KZT', 'Kazakhstani tenge', '₸');
INSERT INTO public.currencies (id, code, full_name, sign) VALUES (14, 'KRW', 'South Korean won', '₩');
INSERT INTO public.currencies (id, code, full_name, sign) VALUES (27, 'MXN', 'Mexican peso', 'Mex$');
INSERT INTO public.currencies (id, code, full_name, sign) VALUES (28, 'SGD', 'Singapore dollar', 'S$');
