INSERT INTO public.currencies (code, full_name, sign) VALUES ('AUD', 'Australian dollar', 'A$');
INSERT INTO public.currencies (code, full_name, sign) VALUES ('USD', 'United States dollar', '$');
INSERT INTO public.currencies (code, full_name, sign) VALUES ('EUR', 'Euro', '€');
INSERT INTO public.currencies (code, full_name, sign) VALUES ('RUB', 'Russian ruble', '₽');
INSERT INTO public.currencies (code, full_name, sign) VALUES ('GBP', 'Pound sterling', '£');
INSERT INTO public.currencies (code, full_name, sign) VALUES ('JPY', 'Japanese yen', '¥');
INSERT INTO public.currencies (code, full_name, sign) VALUES ('CNY', 'Chinese yuan', '¥');
INSERT INTO public.currencies (code, full_name, sign) VALUES ('CHF', 'Swiss franc', 'CHF');
INSERT INTO public.currencies (code, full_name, sign) VALUES ('CAD', 'Canadian dollar', 'C$');
INSERT INTO public.currencies (code, full_name, sign) VALUES ('NZD', 'New Zealand dollar', 'NZ$');
INSERT INTO public.currencies (code, full_name, sign) VALUES ('TRY', 'Turkish lira', '₺');
INSERT INTO public.currencies (code, full_name, sign) VALUES ('THB', 'Thai baht', '฿');
INSERT INTO public.currencies (code, full_name, sign) VALUES ('KZT', 'Kazakhstani tenge', '₸');
INSERT INTO public.currencies (code, full_name, sign) VALUES ('KRW', 'South Korean won', '₩');
INSERT INTO public.currencies (code, full_name, sign) VALUES ('MXN', 'Mexican peso', 'Mex$');
INSERT INTO public.currencies (code, full_name, sign) VALUES ('SGD', 'Singapore dollar', 'S$');